# Khai báo thư viện

In [36]:
import pandas as pd

# Load data

In [37]:
df = pd.read_csv("/content/bike_buyers.csv")

# EDA

In [38]:
df.head()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12496,M,F,"$40.000,00",1,Bachelors,Skilled Manual,Yes,0,0-1 Miles,Europe,42,No
1,24107,M,M,"$30.000,00",3,Partial College,Clerical,Yes,1,0-1 Miles,Europe,43,No
2,14177,M,M,"$80.000,00",5,Partial College,Professional,No,2,2-5 Miles,Europe,60,No
3,24381,S,M,"$70.000,00",0,Bachelors,Professional,Yes,1,5-10 Miles,Pacific,41,Yes
4,25597,S,M,"$30.000,00",0,Bachelors,Clerical,No,0,0-1 Miles,Europe,36,Yes

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026 entries, 0 to 1025
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1026 non-null   int64
 1   Marital Status    1026 non-null   object
 2   Gender            1026 non-null   object
 3   Income            1026 non-null   object
 4   Children          1026 non-null   int64
 5   Education         1026 non-null   object
 6   Occupation        1026 non-null   object
 7   Home Owner        1026 non-null   object
 8   Cars              1026 non-null   int64
 9   Commute Distance  1026 non-null   object
 10  Region            1026 non-null   object
 11  Age               1026 non-null   int64
 12  Purchased Bike    1026 non-null   object
dtypes: int64(4), object(9)
memory usage: 104.3+ KB

In [40]:
df.ID.nunique()

1000

In [41]:
df.ID.value_counts()

ID
16466    2
18299    2
18283    2
17841    2
12590    2
        ..
17238    1
23608    1
22538    1
12332    1
13683    1
Name: count, Length: 1000, dtype: int64

Trường thông tin "Income" là thu nhập lẽ ra phải là kiểu dữ liệu Int thay vì object => cần xem xét lại.

Đối với cột ID, phần lớn các giá trị là duy nhất, tuy nhiên vẫn tồn tại một số trường hợp trùng lặp. Cần tiến hành rà soát và nhóm các khách hàng có cùng ID lại với nhau, vì mục tiêu của bài toán là phân tích hành vi khách hàng mua xe đạp. Điều này sẽ giúp tránh sai lệch trong kết quả và phản ánh đúng dữ liệu thực tế.

In [42]:
df["Marital Status"].value_counts()

Marital Status
M    549
S    477
Name: count, dtype: int64

In [43]:
df.Gender.value_counts()

Gender
M    525
F    501
Name: count, dtype: int64

In [44]:
df.Income.value_counts()

Income
$60.000,00     166
$40.000,00     159
$30.000,00     140
$70.000,00     125
$80.000,00      94
$20.000,00      78
$10.000,00      76
$90.000,00      40
$50.000,00      40
$130.000,00     32
$100.000,00     30
$120.000,00     19
$110.000,00     16
$170.000,00      4
$150.000,00      4
$160.000,00      3
Name: count, dtype: int64

In [45]:
df.Children.value_counts()

Children
0    289
2    219
1    172
3    136
4    126
5     84
Name: count, dtype: int64

In [46]:
df.Education.value_counts()

Education
Bachelors              311
Partial College        278
High School            184
Graduate Degree        175
Partial High School     78
Name: count, dtype: int64

In [47]:
df.Occupation.value_counts()

Occupation
Professional      280
Skilled Manual    259
Clerical          187
Management        174
Manual            126
Name: count, dtype: int64

In [48]:
df["Home Owner"].value_counts()

Home Owner
Yes    697
No     329
Name: count, dtype: int64

In [49]:
df.Cars.value_counts()

Cars
2    348
1    277
0    254
3     86
4     61
Name: count, dtype: int64

In [50]:
df["Commute Distance"].value_counts()

Commute Distance
0-1 Miles     378
5-10 Miles    197
1-2 Miles     176
2-5 Miles     162
10+ Miles     113
Name: count, dtype: int64

In [51]:
df.Region.value_counts()

Region
North America    508
Europe           316
Pacific          202
Name: count, dtype: int64

In [52]:
df.Age.value_counts()

Age
40    44
35    40
47    40
36    39
38    38
43    36
42    34
32    34
45    32
37    32
34    32
48    29
44    28
41    28
30    27
46    27
31    26
50    26
52    25
53    24
49    23
27    23
39    22
51    22
28    22
59    21
33    21
55    20
29    17
54    17
26    17
56    17
60    15
66    14
62    13
58    12
63    11
64    10
67    10
65     9
61     9
69     8
57     8
25     6
73     4
70     4
68     3
78     2
89     1
80     1
74     1
71     1
72     1
Name: count, dtype: int64

In [53]:
df['Age'].describe()

count    1026.000000
mean       44.138402
std        11.349282
min        25.000000
25%        35.000000
50%        43.000000
75%        52.000000
max        89.000000
Name: Age, dtype: float64

Phạm vi tuổi của khách hàng có vẻ là hợp lý.

# Preprocessing - Tiền xử lý dữ liệu

## Xoá dữ liệu trùng lặp

In [54]:
df = df.drop_duplicates()

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1000 non-null   int64
 1   Marital Status    1000 non-null   object
 2   Gender            1000 non-null   object
 3   Income            1000 non-null   object
 4   Children          1000 non-null   int64
 5   Education         1000 non-null   object
 6   Occupation        1000 non-null   object
 7   Home Owner        1000 non-null   object
 8   Cars              1000 non-null   int64
 9   Commute Distance  1000 non-null   object
 10  Region            1000 non-null   object
 11  Age               1000 non-null   int64
 12  Purchased Bike    1000 non-null   object
dtypes: int64(4), object(9)
memory usage: 109.4+ KB

In [56]:
df.ID.value_counts()

ID
12121    1
12496    1
24107    1
14177    1
24381    1
        ..
11434    1
12697    1
22173    1
19280    1
22155    1
Name: count, Length: 1000, dtype: int64

Dữ liệu đã giảm xuống từ 1026 thành 1000 dòng (số 1000 đúng bằng thống kê số lượng dữ liệu khác nhau của cột ID). Như vậy vấn đề ID trùng nhau là do dữ liệu bị lặp lại.

## Chuyển cột Income về định dạng dữ liệu Int

In [57]:
df['Income'] = (
    df['Income']
    .str.replace('$', '', regex=False)     # bỏ ký hiệu $
    .str.replace('.', '', regex=False)     # bỏ dấu chấm (phân cách nghìn)
    .str.replace(',', '.', regex=False)    # đổi dấu phẩy thành dấu chấm (thập phân)
    .astype(float)                         # chuyển sang float
    .astype(int)                           # chuyển sang int
)

In [58]:
df.Income.value_counts()

Income
60000     165
40000     154
30000     135
70000     124
80000      91
20000      74
10000      73
50000      40
90000      39
130000     32
100000     29
120000     18
110000     16
150000      4
160000      3
170000      3
Name: count, dtype: int64

## Sửa lại giá trị cho cột Marital Status

In [59]:
df['Marital Status'] = df['Marital Status'].map({
    'M': 'Married',
    'S': 'Single'
})

In [60]:
df.head()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12496,Married,F,40000,1,Bachelors,Skilled Manual,Yes,0,0-1 Miles,Europe,42,No
1,24107,Married,M,30000,3,Partial College,Clerical,Yes,1,0-1 Miles,Europe,43,No
2,14177,Married,M,80000,5,Partial College,Professional,No,2,2-5 Miles,Europe,60,No
3,24381,Single,M,70000,0,Bachelors,Professional,Yes,1,5-10 Miles,Pacific,41,Yes
4,25597,Single,M,30000,0,Bachelors,Clerical,No,0,0-1 Miles,Europe,36,Yes

## Sửa lại giá trị cho cột Gender

In [61]:
df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'F': 'Female'
})

In [62]:
df.head()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12496,Married,Female,40000,1,Bachelors,Skilled Manual,Yes,0,0-1 Miles,Europe,42,No
1,24107,Married,Male,30000,3,Partial College,Clerical,Yes,1,0-1 Miles,Europe,43,No
2,14177,Married,Male,80000,5,Partial College,Professional,No,2,2-5 Miles,Europe,60,No
3,24381,Single,Male,70000,0,Bachelors,Professional,Yes,1,5-10 Miles,Pacific,41,Yes
4,25597,Single,Male,30000,0,Bachelors,Clerical,No,0,0-1 Miles,Europe,36,Yes

## Tạo cột phân cụm tuổi tác

In [63]:
df['Age Group'] = df['Age'].apply(
    lambda x: 'Adult(0-30)' if x <= 30
    else 'Middle Age(31-54)' if x <= 54
    else 'Old(54+)'
)

## Thay đổi giá trị trong cột Commute Distance

In [64]:
df['Commute Distance'] = df['Commute Distance'].replace(
    '10+ Miles', 'More than 10 miles '
)

In [65]:
df["Commute Distance"].value_counts()

Commute Distance
0-1 Miles              366
5-10 Miles             192
1-2 Miles              169
2-5 Miles              162
More than 10 miles     111
Name: count, dtype: int64